### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nitad54448** [brianhp2/gandi-automatic-dns#30]
hi
sorry if the question is trivial, I get this error (I used -5 and also -t, same error).
Tried on ubuntu 20.04, got the API key 
---

domain_json:
---
{"code": 404, "message": "The resource could not be found.", "object": "HTTPNotFound", "cause": "Not Found"}
---

No zone_id returned. This is expected with Gandi's test API or if you send a LiveDNS API key to Gandi's legacy API. Use gad's -t flag for testing or the -5 flag for LiveDNS.

**Comment by nitad54448** [comment]
Oh sorry, my mistake : I was trying to update the A record of a subdomain and in the command line I used this subdomain instead of the domain. Problem solved. Works like a charm. thanks

**Comment by brianhp2** [comment]
I'm glad you got it working! I'll close this issue but let me know if you run into any others.
